sudo: required
services:
  - docker
#dewvelpoment file to test the application first
before_install:
  - docker build -t ori/multi-container-react-test -f ./client/dockerfile.dev ./client #build context
#running the test 
script:
- docker run -e CI=true ori/multi-container-react-test npm test

after_success:
  - docker build -t orirothschild/multi-client ./client #build context
  - docker build -t orirothschild/multi-nginx ./nginx #build context
  - docker build -t orirothschild/multi-server ./server #build context
  - docker build -t orirothschild/multi-worker ./worker #build context
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push orirothschild/multi-client
  - docker push orirothschild/multi-nginx
  - docker push orirothschild/multi-server
  - docker push orirothschild/multi-worker